---
title: "The Working Moms"
output:
  html_document:
    theme: cerulean
---
_________________________________________________________________________________________________


```{r echo=TRUE, message=FALSE, warning=FALSE}
#library(data.table)
#cols <- c("PAOC", "AGEP", "MAR", "ESR", "SCHL", "WAGP")
#pusa <- fread("ss13pusa.csv", select = cols)
#pusb <- fread("ss13pusb.csv", select = cols)
#pus <- rbind(pusa, pusb)
#save(pus, file = "pus.Rdata")

```

### Introduction:

Insert introduction here...

### Data:

Insert data section here...

```{r echo=TRUE, message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
setwd("C:/Users/huili/Desktop/Playground/")
load("AmericanMoms/pus.Rdata")

pus$MAR <- factor(pus$MAR)
levels(pus$MAR) <- c("Married", "Widowed", "Divorced", "Separated", "Never married")
pus$ESR <- factor(pus$ESR)
levels(pus$ESR) <- c("Employed", "Employed, not at work", "Unemployed", "Employed", "Employed, not at work", "Not in labor force")
pus$PAOC <- factor(pus$PAOC)
levels(pus$PAOC) <- c("Children under 6", "Children 6 to 17", "Children under 6 and 6 to 17", "No children")
pus$SCHLF <- ifelse(pus$SCHL <= 16, 16, pus$SCHL)
pus$SCHLF <- ifelse(pus$SCHLF >= 17 & pus$SCHLF <= 19, 19, pus$SCHLF)
pus$SCHLF <- factor(pus$SCHLF)
levels(pus$SCHLF) <- c("High school or lower", "Some college", "Associate's degree", "Bachelor's degree", "Master's degree", "Professional degree", "Doctorate degree")

am <- subset(pus, !is.na(PAOC) & PAOC != "No children")
```
### Exploratory data analysis:
```{r echo=TRUE, message=FALSE, warning=FALSE}
ggplot(subset(pus, !is.na(PAOC)), aes(AGEP, group = PAOC)) + 
  geom_bar(binwidth = 1, aes(colour = PAOC, fill = PAOC), alpha = 0.3) +
  xlab("Age") + 
  ylab("Count") + 
  ggtitle("Women by Age")
```
Insert exploratory data analysis here...

```{r echo=TRUE, message=FALSE, warning=FALSE}
ggplot(am, aes(AGEP, group = PAOC)) + 
  geom_histogram(aes(colour = PAOC, fill = PAOC), alpha = 0.3) + 
  xlab("Age") +
  ylab("Density") +
  ggtitle("Age Distribution of the Moms")
```


```{r echo=TRUE, message=FALSE, warning=FALSE}
data <- as.data.frame(prop.table(table(am$PAOC, am$MAR)))
data$margin <- prop.table(table(am$PAOC))
data$height <- data$Freq/data$margin
data$center <- c(0, cumsum(data$margin)[1:length(levels(am$PAOC)) -1]) + data$margin/2
ggplot(data, aes(center, height)) + 
  geom_bar(stat = "identity", aes(width = margin, fill = Var2), col = "gray") +
  xlab("Children under 6           Children 6 to 17     Children under 6 and 6 to 17") +
  ylab("Marital Status") + 
  ggtitle("Marital Status of the Moms")
```


```{r echo=TRUE, message=FALSE, warning=FALSE}
data <- as.data.frame(prop.table(table(am$PAOC, am$ESR)))
data$margin <- prop.table(table(am$PAOC))
data$height <- data$Freq/data$margin
data$center <- c(0, cumsum(data$margin)[1:length(levels(am$PAOC)) -1]) + data$margin/2
ggplot(data, aes(center, height)) + 
  geom_bar(stat = "identity", aes(width = margin, fill = Var2), col = "gray") +
  xlab("Children under 6           Children 6 to 17     Children under 6 and 6 to 17") +
  ylab("Employment Status") + 
  ggtitle("Employment Status of the Moms")
```


```{r echo=TRUE, message=FALSE, warning=FALSE}
data <- as.data.frame(prop.table(table(am$PAOC, am$SCHLF)))
data$margin <- prop.table(table(am$PAOC))
data$height <- data$Freq/data$margin
data$center <- c(0, cumsum(data$margin)[1:length(levels(am$PAOC)) -1]) + data$margin/2
ggplot(data, aes(center, height)) + 
  geom_bar(stat = "identity", aes(width = margin, fill = Var2), col = "gray") +
  xlab("Children under 6           Children 6 to 17     Children under 6 and 6 to 17") +
  ylab("Employment Status") + 
  ggtitle("Employment Status of the Moms")
```

```{r echo=TRUE, message=FALSE, warning=FALSE}
data <- as.data.frame(prop.table(table(am$SCHLF, am$ESR), margin = 1))
ggplot(data, aes(x = Var1, y = Freq, group = Var2)) + geom_bar(stat = "identity", aes(colour = Var2, fill = Var2), alpha = 0.3)
```

### Inference:

Insert inference section here...

### Conclusion:

Insert conclusion here...

### References:

Insert references here...

### Appendix:

Insert appendix here...